/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBiTv: typeof import('~icons/bi/tv')['default']
    IBiTV: typeof import('~icons/bi/t-v')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionWithCarousel: typeof import('./src/components/SectionWithCarousel.vue')['default']
    SplitSection: typeof import('./src/components/SplitSection.vue')['default']
  }
}
